### ISSUE TITLE
The Video Chat Bubble is re-rendering multiple times as the agent types message in MessageInput

### ISSUE THREAD

**Issue by tatssato** [hc-institute-japan/Kizuna#36]
This is probably due to the minimum height or width (or both? not sure) that is being set. Every time alice types, the video chat bubble is getting re-rendered on Alice's screen as well as on Bob's screen (because he is receiving the typing signal from alice).

See the video attached for more information.

https://user-images.githubusercontent.com/58587369/119308021-7bf2c480-bca7-11eb-9fa9-477909927d4d.mov

how to reproduce 
1. `npm run build-happ` & `npm run demo`
2. alice adds bob
3. bob adds alice
4. alice sends a video to Bob
5. alice tries to type a text 
6. What is happening in the video will happen

We should, at bare minimum, avoid the re-render because it can be straining to the eye. I think we should discuss what we should do to avoid this problem without spending so much time in the video component part as @nkgardose suggested.

**Comment by nkgardose** [comment]
Fixed this issue in this [commit](https://github.com/hc-institute-japan/Kizuna/commit/b06b234f5c68816537bef652c782a71c9a02058f)

**Comment by tatssato** [comment]
Currently, the height and width are not changing anymore but the blinking still occurs so I will need to reopen this issue.


https://user-images.githubusercontent.com/58587369/123537977-573db100-d76d-11eb-9d95-c1642e937855.mov
